
version: 2

models:
    - name: 311_complaint_data
      description: "311 Complaints Dataset"
      columns:
          - name: Unique_Key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: weather_data
      description: "Weather Dataset"
      columns:
          - name: data
            description: "Date Field"
            tests:
                - unique
                - not_null
